// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.FileExplorer.Extensions.Shell.T4Resources
namespace ISI.FileExplorer.Extensions.Shell
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.FileExplorer.Extensions.Shell.";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork.", T4Resources._root());
			}
		
			public static readonly string AssemblyNameBindingRedirect_ico = _root() + "AssemblyNameBindingRedirect.ico";
			public static System.IO.Stream GetAssemblyNameBindingRedirect_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(AssemblyNameBindingRedirect_ico);
			}
			public static readonly string Cake_16x16_png = _root() + "Cake-16x16.png";
			public static System.IO.Stream GetCake_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Cake_16x16_png);
			}
			public static readonly string Cake_ico = _root() + "Cake.ico";
			public static System.IO.Stream GetCake_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Cake_ico);
			}
			public static readonly string cscss_ico = _root() + "cscss.ico";
			public static System.IO.Stream Getcscss_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(cscss_ico);
			}
			public static readonly string csjs_ico = _root() + "csjs.ico";
			public static System.IO.Stream Getcsjs_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(csjs_ico);
			}
			public static readonly string csless_ico = _root() + "csless.ico";
			public static System.IO.Stream Getcsless_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(csless_ico);
			}
			public static readonly string Jenkins_ico = _root() + "Jenkins.ico";
			public static System.IO.Stream GetJenkins_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Jenkins_ico);
			}
			public static readonly string jenkinsConfig_16x16_png = _root() + "jenkinsConfig-16x16.png";
			public static System.IO.Stream GetjenkinsConfig_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(jenkinsConfig_16x16_png);
			}
			public static readonly string jenkinsConfig_32x32_png = _root() + "jenkinsConfig-32x32.png";
			public static System.IO.Stream GetjenkinsConfig_32x32_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(jenkinsConfig_32x32_png);
			}
			public static readonly string JenkinsOverlay_ico = _root() + "JenkinsOverlay.ico";
			public static System.IO.Stream GetJenkinsOverlay_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(JenkinsOverlay_ico);
			}
			public static readonly string Lantern_ico = _root() + "Lantern.ico";
			public static System.IO.Stream GetLantern_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Lantern_ico);
			}
			public static readonly string Lantern_png = _root() + "Lantern.png";
			public static System.IO.Stream GetLantern_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Lantern_png);
			}
		}
	}
}
#endregion


