#region Copyright & License
/*
Copyright (c) 2026, Integrated Solutions, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

		* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
		* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
		* Neither the name of the Integrated Solutions, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#endregion
 

// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#pragma warning disable CS8981

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

#region ISI.FileExplorer.Extensions.Shell.T4Resources
namespace ISI.FileExplorer.Extensions.Shell
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Resources
	{
		public static string _root()
		{
			return "ISI.FileExplorer.Extensions.Shell.";
		}
	
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Artwork
		{
			public static string _root()
			{
				return string.Format("{0}Artwork.", T4Resources._root());
			}
		
			public static readonly string Ant_16x16_png = _root() + "Ant-16x16.png";
			public static System.IO.Stream GetAnt_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Ant_16x16_png);
			}
			public static readonly string Ant_ico = _root() + "Ant.ico";
			public static System.IO.Stream GetAnt_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Ant_ico);
			}
			public static readonly string AssemblyNameBindingRedirect_ico = _root() + "AssemblyNameBindingRedirect.ico";
			public static System.IO.Stream GetAssemblyNameBindingRedirect_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(AssemblyNameBindingRedirect_ico);
			}
			public static readonly string Cake_16x16_png = _root() + "Cake-16x16.png";
			public static System.IO.Stream GetCake_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Cake_16x16_png);
			}
			public static readonly string Cake_ico = _root() + "Cake.ico";
			public static System.IO.Stream GetCake_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Cake_ico);
			}
			public static readonly string cscss_ico = _root() + "cscss.ico";
			public static System.IO.Stream Getcscss_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(cscss_ico);
			}
			public static readonly string csjs_ico = _root() + "csjs.ico";
			public static System.IO.Stream Getcsjs_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(csjs_ico);
			}
			public static readonly string csless_ico = _root() + "csless.ico";
			public static System.IO.Stream Getcsless_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(csless_ico);
			}
			public static readonly string Jenkins_ico = _root() + "Jenkins.ico";
			public static System.IO.Stream GetJenkins_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Jenkins_ico);
			}
			public static readonly string jenkinsConfig_16x16_png = _root() + "jenkinsConfig-16x16.png";
			public static System.IO.Stream GetjenkinsConfig_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(jenkinsConfig_16x16_png);
			}
			public static readonly string jenkinsConfig_32x32_png = _root() + "jenkinsConfig-32x32.png";
			public static System.IO.Stream GetjenkinsConfig_32x32_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(jenkinsConfig_32x32_png);
			}
			public static readonly string JenkinsOverlay_ico = _root() + "JenkinsOverlay.ico";
			public static System.IO.Stream GetJenkinsOverlay_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(JenkinsOverlay_ico);
			}
			public static readonly string Lantern_ico = _root() + "Lantern.ico";
			public static System.IO.Stream GetLantern_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Lantern_ico);
			}
			public static readonly string Lantern_png = _root() + "Lantern.png";
			public static System.IO.Stream GetLantern_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(Lantern_png);
			}
			public static readonly string nginx_ico = _root() + "nginx.ico";
			public static System.IO.Stream Getnginx_icoStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(nginx_ico);
			}
			public static readonly string nginxConfig_16x16_png = _root() + "nginxConfig-16x16.png";
			public static System.IO.Stream GetnginxConfig_16x16_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(nginxConfig_16x16_png);
			}
			public static readonly string nginxConfig_225x225_png = _root() + "nginxConfig-225x225.png";
			public static System.IO.Stream GetnginxConfig_225x225_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(nginxConfig_225x225_png);
			}
			public static readonly string nginxConfig_32x32_png = _root() + "nginxConfig-32x32.png";
			public static System.IO.Stream GetnginxConfig_32x32_pngStream()
			{
				return typeof(ISI.FileExplorer.Extensions.Shell.T4Resources).Assembly.GetManifestResourceStream(nginxConfig_32x32_png);
			}
		}
	}
}
#endregion


